[package]
name = "wasm-bindgen-futures"
version = "0.2.16"
authors = ["The wasm-bindgen Developers"]

[dependencies]
futures = "0.1.20"
js-sys = { path = "../js-sys", version = '0.2.1' }
wasm-bindgen = { path = "../..", version = '0.2.16' }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = { path = '../test', version = '0.2.16' }
