language: rust
sudo: false

matrix:
  include:
    - rust: nightly

install:
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
  - source ~/.nvm/nvm.sh
  - nvm install 9
  - yarn

script:
  - rustup target add wasm32-unknown-unknown
  - cargo test
  - cargo install --debug --path crates/wasm-bindgen-cli

notifications:
  email:
    on_success: never

