language: rust
sudo: false

matrix:
  include:
    - rust: nightly

script:
  - rustup target add wasm32-unknown-unknown
  - cargo test
  - cargo install --debug --path crates/wasm-bindgen-cli

notifications:
  email:
    on_success: never

