[package]
name = "wasm-bindgen"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]

[lib]
test = false
doctest = false

[dependencies]
wasm-bindgen-macro = { path = "crates/wasm-bindgen-macro" }

[dev-dependencies]
test-support = { path = "crates/test-support" }

[workspace]
members = [
  "crates/wasm-bindgen-cli",
  "examples/hello_world",
]
