[package]
name = "wasm-bindgen-cli-support"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]

[dependencies]
parity-wasm = "0.23"
failure = "0.1"
wasm-bindgen-shared = { path = "../wasm-bindgen-shared" }
serde_json = "1.0"
base64 = "0.9"
