[package]
name = "wasm-bindgen-cli-support"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]

[dependencies]
base64 = "0.9"
parity-wasm = "0.27"
serde_json = "1.0"
wasm-bindgen-shared = { path = "../wasm-bindgen-shared" }
wasm-gc-api = "0.1"
