[package]
name = "console_log"
version = "0.1.0"
authors = ["The wasm-bindgen Developers"]

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.28"
web-sys = { version = "0.3.5", features = ['console'] }
