[package]
name = "performance"
version = "0.1.0"
authors = ["The wasm-bindgen Developers"]

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = { path = "../.." }
humantime = "1"

[dependencies.web-sys]
path = '../../crates/web-sys'
features = ['Window', 'Performance', 'PerformanceTiming']
