[package]
name = "wasm-bindgen-backend"
version = "0.2.0"
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]

[dependencies]
quote = '0.5'
proc-macro2 = { version = "0.3", features = ["nightly"] }
wasm-bindgen-shared = { path = "../shared", version = "0.2.0" }
syn = { version = '0.13', features = ['full'] }
