[package]
name = "wasm-bindgen-backend"
version = "0.2.0"
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/alexcrichton/wasm-bindgen"
homepage = "https://github.com/alexcrichton/wasm-bindgen"
documentation = "https://docs.rs/wasm-bindgen-backend"
description = """
Backend code generation of the wasm-bindgen tool
"""

[dependencies]
quote = '0.5'
proc-macro2 = { version = "0.3", features = ["nightly"] }
wasm-bindgen-shared = { path = "../shared", version = "0.2.0" }
syn = { version = '0.13', features = ['full'] }
