[package]
name = "wasm-bindgen-macro"
version = "0.2.6"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/alexcrichton/wasm-bindgen"
homepage = "https://github.com/alexcrichton/wasm-bindgen"
documentation = "https://docs.rs/wasm-bindgen"
description = """
Definition of the `#[wasm_bindgen]` attribute, an internal dependency
"""

[lib]
proc-macro = true

[features]
spans = ["proc-macro2/nightly", "wasm-bindgen-backend/spans"]

[dependencies]
syn = { version = '0.13', features = ['full'] }
quote = '0.5'
proc-macro2 = "0.3"
serde_json = "1"
wasm-bindgen-shared = { path = "../shared", version = "=0.2.6" }
wasm-bindgen-backend = { path = "../backend", version = "=0.2.6" }
