[package]
name = "dom"
version = "0.1.0"
authors = ["The wasm-bindgen Developers"]

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = { path = "../.." }

[dependencies.web-sys]
path = '../../crates/web-sys'
features = [
  'Document',
  'Element',
  'HtmlElement',
  'Node',
  'Window',
]
