[package]
name = "ui-tests"
version = "0.1.0"
authors = ["The wasm-bindgen Developers"]

[lib]
path = "test.rs"
doctest = false
harness = false

[dependencies]
wasm-bindgen = { path = "../../.." }

[dev-dependencies]
compiletest_rs = "0.3"
